# Generated by Django 5.0 on 2023-12-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_student_nbr_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='student_code',
        ),
    ]
