# Generated by Django 5.0 on 2023-12-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_last_name_student_student_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='subject',
            new_name='name',
        ),
    ]
