# Generated by Django 5.0 on 2023-12-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_grade_options_rename_subject_grade_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
    ]
